/**
 * Master Reading Articles Dataset for LinguaFlow Web App
 */

import { ReadingArticle } from '@linguaflow/domain';

export const MASTER_READING_ARTICLES: ReadingArticle[] = [
  // ==========================================================================
  // CEFR A1 ARTICLES (3 articles)
  // ==========================================================================
  {
    id: 'a1-morning-coffee',
    title: 'Morning Routines Around the World',
    subtitle: 'How people start their fresh day with simple habits',
    level: 'A1',
    topic: 'Daily Life',
    author: 'LinguaFlow Editorial Team',
    estimatedMinutes: 2,
    wordCount: 165,
    coverImage: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-coffee', 'vocab-morning', 'vocab-breakfast', 'vocab-energy', 'vocab-relax'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Every morning, millions of people wake up and drink a hot cup of coffee or tea. A healthy morning routine gives people energy and helps them focus on daily work.',
        vietnamese: 'Mỗi buổi sáng, hàng triệu người thức dậy và uống một tách cà phê hoặc trà nóng. Một thói quen buổi sáng lành mạnh tiếp thêm năng lượng và giúp họ tập trung vào công việc hàng ngày.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'In Vietnam, many people enjoy iced milk coffee on the sidewalk with friends. In Italy, people quickly drink an espresso at a coffee bar before going to their offices.',
        vietnamese: 'Ở Việt Nam, nhiều người thích thưởng thức cà phê sữa đá trên vỉa hè cùng bạn bè. Ở Ý, mọi người uống nhanh một tách espresso tại quầy cà phê trước khi đến văn phòng.',
      },
      {
        id: 'p3',
        order: 3,
        english: 'Starting the morning with good food and a warm drink is an enjoyable habit in almost every country.',
        vietnamese: 'Bắt đầu buổi sáng với món ăn ngon và đồ uống ấm là thói quen thú vị ở hầu hết mọi quốc gia.',
      },
    ],
    questions: [
      {
        id: 'q1-1',
        type: 'main-idea',
        question: 'What is the main idea of the article?',
        options: ['Different morning habits worldwide', 'How to make Italian espresso', 'Why coffee is bad for health', 'The history of tea'],
        correctAnswer: 'Different morning habits worldwide',
        explanation: 'The text describes morning beverage and breakfast routines in various countries.',
        difficulty: 'A1',
        relatedParagraph: 1,
      },
      {
        id: 'q1-2',
        type: 'true-false',
        question: 'In Italy, people usually drink iced milk coffee on the sidewalk.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Paragraph 2 explains that iced milk coffee on sidewalks is in Vietnam, whereas Italians drink espresso at coffee bars.',
        difficulty: 'A1',
        relatedParagraph: 2,
      },
      {
        id: 'q1-3',
        type: 'vocabulary-context',
        question: 'What does the word "energy" mean in paragraph 1?',
        options: ['The strength and vitality to be active', 'A type of hot drink', 'The cost of breakfast', 'A sidewalk cafe'],
        correctAnswer: 'The strength and vitality to be active',
        explanation: 'Energy in this context refers to physical and mental power to perform daily work.',
        difficulty: 'A1',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'a1-city-library',
    title: 'A Visit to the City Library',
    subtitle: 'Quiet spaces for reading, studying and discovering books',
    level: 'A1',
    topic: 'Education',
    author: 'Elena Rostova',
    estimatedMinutes: 2,
    wordCount: 155,
    coverImage: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-library', 'vocab-book', 'vocab-quiet', 'vocab-borrow', 'vocab-student'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'The city library is a peaceful place in the center of town. It has thousands of books on many topics, including science, history, art, and language learning.',
        vietnamese: 'Thư viện thành phố là một nơi yên bình ở trung tâm thị trấn. Nơi đây có hàng ngàn cuốn sách về nhiều chủ đề, bao gồm khoa học, lịch sử, nghệ thuật và học ngôn ngữ.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Students come here after school to do homework and prepare for exams. Anyone with a library card can borrow up to five books for two weeks for free.',
        vietnamese: 'Học sinh đến đây sau giờ học để làm bài tập và chuẩn bị cho các kỳ thi. Bất kỳ ai có thẻ thư viện đều có thể mượn tối đa năm cuốn sách trong hai tuần miễn phí.',
      },
    ],
    questions: [
      {
        id: 'q2-1',
        type: 'detail',
        question: 'How many books can a member borrow at one time?',
        options: ['Up to two books', 'Up to five books', 'Unlimited books', 'Ten books'],
        correctAnswer: 'Up to five books',
        explanation: 'Paragraph 2 mentions members can borrow up to five books for two weeks.',
        difficulty: 'A1',
        relatedParagraph: 2,
      },
      {
        id: 'q2-2',
        type: 'true-false',
        question: 'The library is located far away in the countryside.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Paragraph 1 states the library is in the center of town.',
        difficulty: 'A1',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'a1-healthy-eating',
    title: 'Eating Fresh Fruits Every Day',
    subtitle: 'Simple nutritional choices for a healthier body',
    level: 'A1',
    topic: 'Health',
    author: 'Dr. Sarah Jenkins',
    estimatedMinutes: 2,
    wordCount: 150,
    coverImage: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-fruit', 'vocab-healthy', 'vocab-vitamins', 'vocab-apple', 'vocab-water'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Fresh fruits like apples, oranges, and bananas provide essential vitamins. Eating an apple in the afternoon is much healthier than eating sweet candy or chips.',
        vietnamese: 'Trái cây tươi như táo, cam và chuối cung cấp các vitamin thiết yếu. Ăn một quả táo vào buổi chiều lành mạnh hơn nhiều so với ăn kẹo ngọt hay khoai tây chiên.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Doctors recommend drinking plenty of clean water and having at least two servings of fresh fruit every single day.',
        vietnamese: 'Các bác sĩ khuyên nên uống nhiều nước sạch và ăn ít nhất hai khẩu phần trái cây tươi mỗi ngày.',
      },
    ],
    questions: [
      {
        id: 'q3-1',
        type: 'detail',
        question: 'What do doctors recommend drinking every day?',
        options: ['Soda and tea', 'Plenty of clean water', 'Sweet energy drinks', 'Milkshakes'],
        correctAnswer: 'Plenty of clean water',
        explanation: 'Paragraph 2 explicitly states doctors recommend drinking plenty of clean water.',
        difficulty: 'A1',
        relatedParagraph: 2,
      },
    ],
  },

  // ==========================================================================
  // CEFR A2 ARTICLES (3 articles)
  // ==========================================================================
  {
    id: 'a2-train-travel',
    title: 'Traveling by High-Speed Train',
    subtitle: 'Modern and eco-friendly transportation across modern cities',
    level: 'A2',
    topic: 'Travel',
    author: 'Kenji Sato',
    estimatedMinutes: 3,
    wordCount: 210,
    coverImage: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-train', 'vocab-travel', 'vocab-speed', 'vocab-scenery', 'vocab-passenger'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'High-speed trains are becoming the preferred mode of travel in many parts of the world. They connect major cities in just a few hours without the long waiting times found at airports.',
        vietnamese: 'Tàu cao tốc đang trở thành phương tiện di chuyển được ưa chuộng ở nhiều nơi trên thế giới. Chúng kết nối các thành phố lớn chỉ trong vài giờ mà không phải chờ đợi lâu như ở sân bay.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Passengers can relax comfortably in spacious seats, read books, browse the internet using onboard Wi-Fi, and watch breathtaking rural scenery through large windows.',
        vietnamese: 'Hành khách có thể thư giãn thoải mái trên những chiếc ghế rộng rãi, đọc sách, lướt internet qua Wi-Fi trên tàu và ngắm nhìn cảnh quan nông thôn tuyệt đẹp qua những ô cửa sổ lớn.',
      },
      {
        id: 'p3',
        order: 3,
        english: 'Furthermore, electric trains produce significantly less carbon emissions compared to passenger airplanes and private cars.',
        vietnamese: 'Hơn nữa, tàu điện tạo ra lượng khí thải carbon ít hơn đáng kể so với máy bay chở khách và ô tô cá nhân.',
      },
    ],
    questions: [
      {
        id: 'q4-1',
        type: 'multiple-choice',
        question: 'Why do many people prefer high-speed trains over airplanes?',
        options: ['They avoid long airport waiting times', 'They are always free of charge', 'They only operate at night', 'They fly faster than airplanes'],
        correctAnswer: 'They avoid long airport waiting times',
        explanation: 'Paragraph 1 notes trains connect cities in a few hours without long airport waiting times.',
        difficulty: 'A2',
        relatedParagraph: 1,
      },
      {
        id: 'q4-2',
        type: 'detail',
        question: 'What environmental advantage do electric trains have?',
        options: ['They produce less carbon emissions', 'They create more noise pollution', 'They consume petrol', 'They require no electricity'],
        correctAnswer: 'They produce less carbon emissions',
        explanation: 'Paragraph 3 highlights that electric trains produce significantly less carbon emissions.',
        difficulty: 'A2',
        relatedParagraph: 3,
      },
    ],
  },
  {
    id: 'a2-digital-learning',
    title: 'The Rise of Digital Classrooms',
    subtitle: 'How laptops and interactive tablets support modern education',
    level: 'A2',
    topic: 'Education',
    author: 'Maria Gonzales',
    estimatedMinutes: 3,
    wordCount: 200,
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-digital', 'vocab-classroom', 'vocab-tablet', 'vocab-interactive', 'vocab-software'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Technology has transformed traditional classrooms into interactive digital spaces. Students no longer carry heavy stacks of paper textbooks every day.',
        vietnamese: 'Công nghệ đã biến các lớp học truyền thống thành không gian số tương tác. Học sinh không còn phải mang theo những chồng sách giáo khoa giấy nặng nề mỗi ngày.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'With educational software and tablets, learners can complete quizzes, practice listening exercises, and receive instant feedback on their work.',
        vietnamese: 'Với phần mềm giáo dục và máy tính bảng, người học có thể làm bài trắc nghiệm, luyện bài tập nghe và nhận phản hồi ngay lập tức về bài làm của mình.',
      },
    ],
    questions: [
      {
        id: 'q5-1',
        type: 'main-idea',
        question: 'What is the main topic of the text?',
        options: ['How technology improves student learning in classrooms', 'How to manufacture cheap tablets', 'Why paper textbooks are better', 'The history of chalkboard'],
        correctAnswer: 'How technology improves student learning in classrooms',
        explanation: 'The passage explores the benefits of technology and interactive tools in education.',
        difficulty: 'A2',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'a2-urban-gardens',
    title: 'Community Green Spaces in Big Cities',
    subtitle: 'Residents building rooftop gardens for cleaner air and fresh herbs',
    level: 'A2',
    topic: 'Environment',
    author: 'Liam O\'Connor',
    estimatedMinutes: 3,
    wordCount: 190,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-garden', 'vocab-community', 'vocab-vegetables', 'vocab-rooftop', 'vocab-environment'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'In crowded metropolitan cities, green spaces are often rare. However, many residents are now building communal gardens on rooftops and neighborhood corners.',
        vietnamese: 'Tại các đô thị đông đúc, không gian xanh thường rất hiếm. Tuy nhiên, nhiều cư dân hiện đang xây dựng các khu vườn cộng đồng trên sân thượng và các góc phố.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Neighbors work together on weekends to plant tomatoes, herbs, and flowers. These urban gardens help reduce stress and improve local air quality.',
        vietnamese: 'Hàng xóm cùng nhau làm việc vào cuối tuần để trồng cà chua, thảo mộc và hoa. Những khu vườn đô thị này giúp giảm căng thẳng và cải thiện chất lượng không khí địa phương.',
      },
    ],
    questions: [
      {
        id: 'q6-1',
        type: 'true-false',
        question: 'Urban gardens are built on rooftops and neighborhood corners.',
        options: ['True', 'False'],
        correctAnswer: 'True',
        explanation: 'Paragraph 1 confirms rooftop and corner communal gardens.',
        difficulty: 'A2',
        relatedParagraph: 1,
      },
    ],
  },

  // ==========================================================================
  // CEFR B1 ARTICLES (4 articles)
  // ==========================================================================
  {
    id: 'b1-remote-work',
    title: 'The Evolution of Flexible Remote Work',
    subtitle: 'Balancing digital productivity, collaboration, and personal lifestyle',
    level: 'B1',
    topic: 'Work',
    author: 'Hannah Davies',
    estimatedMinutes: 4,
    wordCount: 310,
    coverImage: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-productivity', 'vocab-collaboration', 'vocab-flexibility', 'vocab-commute', 'vocab-distributed'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'The concept of the traditional workplace has shifted dramatically over the past decade. Cloud infrastructure, high-speed fiber internet, and collaborative video platforms have made remote work feasible for millions of professionals across the globe.',
        vietnamese: 'Khái niệm về nơi làm việc truyền thống đã thay đổi ngoạn mục trong thập kỷ qua. Cơ sở hạ tầng đám mây, internet cáp quang tốc độ cao và các nền tảng video cộng tác đã giúp làm việc từ xa trở nên khả thi cho hàng triệu chuyên gia trên toàn cầu.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Employees highlight considerable advantages, such as eliminating long daily commutes in heavy traffic, enjoying greater schedule autonomy, and spending more quality time with family members.',
        vietnamese: 'Nhân viên nêu bật những lợi thế đáng kể, chẳng hạn như loại bỏ việc di chuyển hàng ngày trong tình trạng tắc đường, tận hưởng sự tự chủ về lịch trình và dành nhiều thời gian chất lượng hơn cho gia đình.',
      },
      {
        id: 'p3',
        order: 3,
        english: 'Nevertheless, remote work introduces distinctive challenges. Without clear boundaries between professional obligations and personal leisure, individuals may experience psychological burnout. Successful organizations prioritize transparent communication and intentional social interactions to sustain team cohesion.',
        vietnamese: 'Tuy nhiên, làm việc từ xa cũng mang lại những thách thức riêng. Nếu không có ranh giới rõ ràng giữa nghĩa vụ công việc và nghỉ ngơi cá nhân, cá nhân có thể bị kiệt sức. Các tổ chức thành công luôn ưu tiên giao tiếp minh bạch và các hoạt động tương tác gắn kết đội ngũ.',
      },
    ],
    questions: [
      {
        id: 'q7-1',
        type: 'main-idea',
        question: 'What is the primary focus of the article?',
        options: ['The advantages and challenges of modern remote work', 'How to install cloud software', 'The history of traffic congestion', 'Why offices should be permanently demolished'],
        correctAnswer: 'The advantages and challenges of modern remote work',
        explanation: 'The passage explores both the key benefits and the psychological/collaboration challenges of remote work.',
        difficulty: 'B1',
        relatedParagraph: 1,
      },
      {
        id: 'q7-2',
        type: 'inference',
        question: 'What can be inferred about employees who fail to set boundaries while working from home?',
        options: ['They are at risk of experiencing burnout', 'They will be immediately fired', 'They travel more frequently', 'They earn double salary'],
        correctAnswer: 'They are at risk of experiencing burnout',
        explanation: 'Paragraph 3 states that without clear boundaries between work and leisure, workers may face psychological burnout.',
        difficulty: 'B1',
        relatedParagraph: 3,
      },
    ],
  },
  {
    id: 'b1-ocean-cleanup',
    title: 'Innovative Solutions for Ocean Plastic Cleanup',
    subtitle: 'Engineers deploying floating barriers to capture microplastics and debris',
    level: 'B1',
    topic: 'Environment',
    author: 'Dr. Arthur Vance',
    estimatedMinutes: 4,
    wordCount: 305,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-ecosystem', 'vocab-sustainable', 'vocab-conservation', 'vocab-marine', 'vocab-pollution'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Millions of tons of non-biodegradable plastic enter marine ecosystems every year. Ocean currents concentrate this plastic waste into massive swirling zones known as oceanic garbage patches, which threaten fish, seabirds, and coral reefs.',
        vietnamese: 'Hàng triệu tấn rác thải nhựa không thể phân hủy sinh học đổ vào các hệ sinh thái biển mỗi năm. Các dòng hải lưu gom rác thải nhựa này thành các mảng xoáy rác khổng lồ trên đại dương, đe dọa cá, chim biển và các rạn san hô.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'In response, international environmental teams have designed autonomous floating barrier systems. These U-shaped floating screens harness natural ocean currents and wind to gather debris without harming swimming wildlife.',
        vietnamese: 'Để giải quyết vấn đề này, các nhóm môi trường quốc tế đã thiết kế các hệ thống phao chắn nổi tự hành. Những tấm chắn nổi hình chữ U này tận dụng dòng hải lưu và gió tự nhiên để gom rác mà không gây hại cho sinh vật biển.',
      },
    ],
    questions: [
      {
        id: 'q8-1',
        type: 'detail',
        question: 'How do the U-shaped floating barrier systems collect ocean debris?',
        options: ['By utilizing natural ocean currents and wind', 'By using underwater explosives', 'By dragging large metal nets along the seabed', 'By burning the plastic on ships'],
        correctAnswer: 'By utilizing natural ocean currents and wind',
        explanation: 'Paragraph 2 notes that the floating screens harness natural currents and wind to concentrate debris.',
        difficulty: 'B1',
        relatedParagraph: 2,
      },
    ],
  },
  {
    id: 'b1-language-cognition',
    title: 'How Bilingualism Enhances Cognitive Brain Function',
    subtitle: 'Neuroscience reveals the hidden benefits of mastering a second language',
    level: 'B1',
    topic: 'Science',
    author: 'Prof. Claire Dubois',
    estimatedMinutes: 4,
    wordCount: 300,
    coverImage: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-cognitive', 'vocab-bilingual', 'vocab-neuroscience', 'vocab-memory', 'vocab-articulate'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'For decades, researchers assumed that learning two languages simultaneously might confuse young children. However, contemporary neurological studies demonstrate precisely the opposite outcome: bilingual brains exhibit superior problem-solving agility.',
        vietnamese: 'Trong nhiều thập kỷ, các nhà nghiên cứu từng giả định rằng việc học hai ngôn ngữ cùng lúc có thể làm trẻ nhỏ bối rối. Tuy nhiên, các nghiên cứu thần kinh học hiện đại chứng minh điều hoàn toàn ngược lại: bộ não song ngữ thể hiện sự linh hoạt vượt trội trong giải quyết vấn đề.',
      },
    ],
    questions: [
      {
        id: 'q9-1',
        type: 'true-false',
        question: 'Modern neurological research shows that bilingualism harms memory and problem-solving skills.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Paragraph 1 clarifies that bilingualism strengthens working memory and enhances problem-solving agility.',
        difficulty: 'B1',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'b1-renewable-energy',
    title: 'The Global Transition to Solar and Wind Power',
    subtitle: 'How renewable infrastructure is outcompeting fossil fuels worldwide',
    level: 'B1',
    topic: 'Science',
    author: 'Marcus Lindholm',
    estimatedMinutes: 4,
    wordCount: 290,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-renewable', 'vocab-sustainable', 'vocab-energy', 'vocab-infrastructure', 'vocab-efficiency'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Solar panel efficiency has risen dramatically over recent years while production costs have dropped by more than eighty percent. As a result, solar and wind power are now cheaper to install and operate than newly built coal or gas plants in most countries.',
        vietnamese: 'Hiệu suất pin mặt trời đã tăng đáng kể trong những năm gần đây trong khi chi phí sản xuất giảm hơn tám mươi phần trăm. Nhờ đó, năng lượng mặt trời và gió hiện có chi phí lắp đặt và vận hành rẻ hơn so với các nhà máy than hoặc khí đốt mới ở hầu hết các quốc gia.',
      },
    ],
    questions: [
      {
        id: 'q10-1',
        type: 'detail',
        question: 'By how much have solar production costs decreased?',
        options: ['By more than 80 percent', 'By exactly 10 percent', 'Costs have doubled', 'By less than 5 percent'],
        correctAnswer: 'By more than 80 percent',
        explanation: 'Paragraph 1 states production costs dropped by more than eighty percent.',
        difficulty: 'B1',
        relatedParagraph: 1,
      },
    ],
  },

  // ==========================================================================
  // CEFR B2 ARTICLES (4 articles)
  // ==========================================================================
  {
    id: 'b2-ai-workplace',
    title: 'Artificial Intelligence and the Future of Knowledge Work',
    subtitle: 'Synthesizing creative human insight with generative automated algorithms',
    level: 'B2',
    topic: 'Technology',
    author: 'Dr. Samuel Vance',
    estimatedMinutes: 5,
    wordCount: 380,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-transform', 'vocab-intelligence', 'vocab-paradigm', 'vocab-automation', 'vocab-critical'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'The rapid emergence of generative artificial intelligence models has catalyzed profound transformations across software engineering, graphic design, and financial analysis. Unlike previous waves of industrial automation that predominantly replaced manual labor, AI now replicates cognitive and analytical workflows.',
        vietnamese: 'Sự xuất hiện nhanh chóng của các mô hình trí tuệ nhân tạo tạo sinh đã thúc đẩy những chuyển đổi sâu sắc trong kỹ thuật phần mềm, thiết kế đồ họa và phân tích tài chính. Không giống như các làn sóng tự động hóa công nghiệp trước đây chủ yếu thay thế lao động chân tay, AI hiện mô phỏng các quy trình làm việc nhận thức và phân tích.',
      },
      {
        id: 'p2',
        order: 2,
        english: 'Rather than eliminating knowledge workers outright, cutting-edge organizations are adopting augmented intelligence paradigms. In these environments, algorithms rapidly synthesize vast datasets, draft initial code repositories, and identify patterns, leaving human experts to focus on strategic judgment, ethical oversight, and empathetic client consultation.',
        vietnamese: 'Thay vì loại bỏ hoàn toàn lao động tri thức, các tổ chức tiên phong đang áp dụng mô hình trí tuệ tăng cường. Trong các môi trường này, thuật toán nhanh chóng tổng hợp các tập dữ liệu khổng lồ, phác thảo mã nguồn ban đầu và nhận diện các quy luật, giúp các chuyên gia con người tập trung vào đánh giá chiến lược, giám sát đạo đức và tư vấn khách hàng thấu cảm.',
      },
    ],
    questions: [
      {
        id: 'q11-1',
        type: 'main-idea',
        question: 'What is the central thesis of the article regarding AI in knowledge work?',
        options: [
          'AI is augmenting human workers by handling routine analytical tasks while elevating strategic and ethical responsibilities.',
          'AI will immediately eradicate all software engineers and financial analysts within two years.',
          'Industrial automation is superior to generative artificial intelligence.',
          'Human empathy has become irrelevant in contemporary corporate consulting.',
        ],
        correctAnswer: 'AI is augmenting human workers by handling routine analytical tasks while elevating strategic and ethical responsibilities.',
        explanation: 'Paragraph 2 highlights augmented intelligence where algorithms process data while humans oversee strategy and ethics.',
        difficulty: 'B2',
        relatedParagraph: 2,
      },
    ],
  },
  {
    id: 'b2-microbiome-health',
    title: 'The Human Microbiome and Metabolic Longevity',
    subtitle: 'Unlocking how trillions of gut bacteria regulate immune and cognitive health',
    level: 'B2',
    topic: 'Health',
    author: 'Prof. Evelyn Reed',
    estimatedMinutes: 5,
    wordCount: 360,
    coverImage: 'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-microbiome', 'vocab-metabolism', 'vocab-bacteria', 'vocab-immunity', 'vocab-crucial'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Inside the human gastrointestinal tract reside trillions of microorganisms collectively termed the gut microbiome. Far from being passive inhabitants, these diverse bacterial colonies produce vital neurotransmitters, regulate metabolic homeostasis, and train our adaptive immune system.',
        vietnamese: 'Bên trong đường tiêu hóa của con người có hàng nghìn tỷ vi sinh vật cùng tồn tại, được gọi chung là hệ vi sinh vật đường ruột. Không hề là những cư dân thụ động, các quần thể vi khuẩn đa dạng này sản sinh các chất dẫn truyền thần kinh quan trọng, điều hòa sự cân bằng trao đổi chất và rèn luyện hệ thống miễn dịch thích ứng.',
      },
    ],
    questions: [
      {
        id: 'q12-1',
        type: 'detail',
        question: 'What crucial physiological roles do gut bacteria perform?',
        options: [
          'They produce neurotransmitters and train the adaptive immune system',
          'They strictly cause infectious diseases',
          'They eliminate the need for dietary vitamins',
          'They permanently shut down metabolic processes',
        ],
        correctAnswer: 'They produce neurotransmitters and train the adaptive immune system',
        explanation: 'Paragraph 1 explains that gut colonies produce vital neurotransmitters and train the immune system.',
        difficulty: 'B2',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'b2-space-telescopes',
    title: 'Deep Space Observatories and the Origins of Cosmic Galaxies',
    subtitle: 'Infrared imaging revealing early stellar structures formed after the Big Bang',
    level: 'B2',
    topic: 'Science',
    author: 'Dr. Neil Sterling',
    estimatedMinutes: 5,
    wordCount: 370,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-cosmic', 'vocab-telescope', 'vocab-infrared', 'vocab-galaxy', 'vocab-astronomy'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'By positioning sophisticated optical mirrors millions of kilometers into space, deep space observatories evade atmospheric turbulence and light pollution. High-precision infrared instruments peer through dense interstellar dust clouds to capture ancient light emitted over thirteen billion years ago.',
        vietnamese: 'Bằng cách đặt các gương quang học tinh vi cách xa hàng triệu km ngoài không gian, các đài thiên văn vũ trụ sâu tránh được sự nhiễu loạn khí quyển và ô nhiễm ánh sáng. Các thiết bị hồng ngoại độ chính xác cao nhìn xuyên qua các đám mây bụi liên sao dày đặc để ghi lại ánh sáng cổ xưa phát ra từ hơn mười ba tỷ năm trước.',
      },
    ],
    questions: [
      {
        id: 'q13-1',
        type: 'true-false',
        question: 'Space observatories suffer from the same atmospheric light pollution as ground-based telescopes.',
        options: ['True', 'False'],
        correctAnswer: 'False',
        explanation: 'Paragraph 1 explains that space observatories evade atmospheric turbulence and light pollution.',
        difficulty: 'B2',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'b2-sustainable-architecture',
    title: 'Biophilic Urbanism and Carbon-Neutral Architecture',
    subtitle: 'Re-integrating living botanical ecosystems into skyscrapers and public plazas',
    level: 'B2',
    topic: 'Environment',
    author: 'Renata Rossi',
    estimatedMinutes: 5,
    wordCount: 350,
    coverImage: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-sustainable', 'vocab-architecture', 'vocab-biophilic', 'vocab-carbon', 'vocab-efficiency'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Biophilic architecture integrates living botanical systems directly into high-rise facades and corporate headquarters. Vertical forest towers absorb carbon dioxide, dampen urban street acoustics, and dramatically reduce internal cooling requirements during sweltering summers.',
        vietnamese: 'Kiến trúc ưa sinh học tích hợp các hệ thống thực vật sống trực tiếp vào mặt đứng của các tòa nhà chọc trời và trụ sở công ty. Các tháp rừng thẳng đứng hấp thụ carbon dioxide, giảm tiếng ồn đường phố đô thị và giảm đáng kể nhu cầu làm mát bên trong trong những mùa hè oi bức.',
      },
    ],
    questions: [
      {
        id: 'q14-1',
        type: 'detail',
        question: 'What is one major thermal benefit of vertical forest towers?',
        options: [
          'They dramatically reduce internal cooling requirements in summer',
          'They eliminate the need for building foundations',
          'They generate toxic greenhouse gases',
          'They heat buildings excessively',
        ],
        correctAnswer: 'They dramatically reduce internal cooling requirements in summer',
        explanation: 'Paragraph 1 notes that vertical forests reduce cooling requirements during hot summers.',
        difficulty: 'B2',
        relatedParagraph: 1,
      },
    ],
  },

  // ==========================================================================
  // CEFR C1 ARTICLES (2 articles)
  // ==========================================================================
  {
    id: 'c1-neuroplasticity',
    title: 'Epigenetics, Neuroplasticity, and Lifelong Cognitive Adaptation',
    subtitle: 'How environmental stimuli and deliberate practice continually remodel human neural circuitry',
    level: 'C1',
    topic: 'Science',
    author: 'Prof. Alexander Wright',
    estimatedMinutes: 6,
    wordCount: 450,
    coverImage: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-neuroplasticity', 'vocab-epigenetics', 'vocab-synaptic', 'vocab-cognitive', 'vocab-articulate'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'Historical dogmas in neurological sciences posited that the adult mammalian brain was functionally immutable following early developmental critical periods. Contemporary research has thoroughly dismantled this deterministic viewpoint, establishing neuroplasticity—the capacity of synaptic architecture to structurally reorganize in response to experiential demands—as a persistent lifelong phenomenon.',
        vietnamese: 'Các học thuyết lịch sử trong khoa học thần kinh từng cho rằng bộ não động vật có vú trưởng thành không thể thay đổi về mặt chức năng sau các giai đoạn phát triển quan trọng ban đầu. Nghiên cứu đương đại đã hoàn toàn bác bỏ quan điểm tất định này, khẳng định tính khả biến thần kinh—khả năng cấu trúc khớp thần kinh tái tổ chức để đáp ứng với các yêu cầu trải nghiệm—là một hiện tượng dai dẳng suốt đời.',
      },
    ],
    questions: [
      {
        id: 'q15-1',
        type: 'inference',
        question: 'What historical assumption about the adult brain has contemporary neuroscience disproven?',
        options: [
          'That the adult brain is rigid and structurally unchangeable after early childhood development',
          'That neurons require oxygen and blood circulation to survive',
          'That memory recall is completely impossible in human beings',
          'That linguistic practice has no influence on spoken communication',
        ],
        correctAnswer: 'That the adult brain is rigid and structurally unchangeable after early childhood development',
        explanation: 'Paragraph 1 discusses how historical dogmas believed the adult brain was immutable, which modern neuroplasticity research has disproven.',
        difficulty: 'C1',
        relatedParagraph: 1,
      },
    ],
  },
  {
    id: 'c1-linguistic-relativity',
    title: 'Linguistic Relativity and the Architecture of Human Conceptualization',
    subtitle: 'Examining the Sapir-Whorf hypothesis through contemporary empirical psycholinguistics',
    level: 'C1',
    topic: 'Culture',
    author: 'Dr. Beatrice Thorne',
    estimatedMinutes: 6,
    wordCount: 440,
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=700&auto=format&fit=crop&q=80',
    vocabularyIds: ['vocab-linguistic', 'vocab-conceptual', 'vocab-paradigm', 'vocab-syntax', 'vocab-articulate'],
    paragraphs: [
      {
        id: 'p1',
        order: 1,
        english: 'The linguistic relativity hypothesis posits that the particular structural characteristics of a natural language shape the habitual thought patterns and perceptual categorizations of its speakers. While deterministic formulations of this principle have been largely abandoned, nuanced empirical investigations reveal that grammatical gender, spatial framing, and color terminology subtly influence non-linguistic mental representations.',
        vietnamese: 'Giả thuyết tính tương đối của ngôn ngữ cho rằng các đặc điểm cấu trúc cụ thể của một ngôn ngữ tự nhiên sẽ định hình thói quen tư duy và sự phân loại nhận thức của người nói. Mặc dù các công thức tất định tuyệt đối của nguyên lý này phần lớn đã bị loại bỏ, các cuộc điều tra thực nghiệm tinh vi cho thấy giống ngữ pháp, khung không gian và thuật ngữ màu sắc ảnh hưởng tinh tế đến các biểu tượng tinh thần phi ngôn ngữ.',
      },
    ],
    questions: [
      {
        id: 'q16-1',
        type: 'main-idea',
        question: 'What is the primary perspective presented regarding the linguistic relativity hypothesis?',
        options: [
          'Nuanced empirical evidence indicates language structure subtly influences perceptual and mental representations',
          'Language completely and immutably imprisons human perception with zero exceptions',
          'All languages across the world share identical grammatical gender conventions',
          'Human thought is entirely independent of any vocabulary or grammatical systems',
        ],
        correctAnswer: 'Nuanced empirical evidence indicates language structure subtly influences perceptual and mental representations',
        explanation: 'Paragraph 1 explains that while radical determinism is rejected, language features subtly shape non-linguistic representations.',
        difficulty: 'C1',
        relatedParagraph: 1,
      },
    ],
  },
];
