/**
 * Master Sample Vocabulary Dataset for LinguaFlow Smart Vocabulary Lab
 * Covers CEFR A1, A2, B1, B2, C1 across core everyday, business, and academic topics.
 */

import { VocabularyWord } from '@linguaflow/domain';

export const MASTER_VOCABULARY_LIST: VocabularyWord[] = [
  // ==========================================================================
  // LEVEL A1: BEGINNER (CƠ BẢN)
  // ==========================================================================
  {
    id: 'vocab-hello',
    targetText: 'Hello',
    normalizedText: 'hello',
    translation: 'Xin chào',
    phoneticUs: '/həˈloʊ/',
    phoneticUk: '/həˈləʊ/',
    partOfSpeech: 'interjection',
    cefrLevel: 'A1',
    category: 'Daily Life',
    definitionEn: 'Used as a greeting or to begin a conversation.',
    examples: [
      { sentence: 'Hello, how are you today?', translation: 'Xin chào, hôm nay bạn thế nào?' },
      { sentence: 'She said hello with a bright smile.', translation: 'Cô ấy chào với một nụ cười rạng rỡ.' },
    ],
    synonyms: ['hi', 'greetings'],
    imageUrl: 'https://images.unsplash.com/photo-1577563908411-5077b6dc7624?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['greetings', 'basics'],
  },
  {
    id: 'vocab-student',
    targetText: 'Student',
    normalizedText: 'student',
    translation: 'Học sinh / Sinh viên',
    phoneticUs: '/ˈstuːdənt/',
    phoneticUk: '/ˈstjuːdnt/',
    partOfSpeech: 'noun',
    cefrLevel: 'A1',
    category: 'Education',
    definitionEn: 'A person who is studying at a school, college, or university.',
    examples: [
      { sentence: 'He is an enthusiastic university student.', translation: 'Anh ấy là một sinh viên đại học nhiệt huyết.' },
      { sentence: 'The student asked an insightful question.', translation: 'Người học sinh đã đặt một câu hỏi sâu sắc.' },
    ],
    synonyms: ['learner', 'pupil'],
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['school', 'study'],
  },
  {
    id: 'vocab-coffee',
    targetText: 'Coffee',
    normalizedText: 'coffee',
    translation: 'Cà phê',
    phoneticUs: '/ˈkɔːfi/',
    phoneticUk: '/ˈkɒfi/',
    partOfSpeech: 'noun',
    cefrLevel: 'A1',
    category: 'Food & Drink',
    definitionEn: 'A hot drink made from roasted and ground coffee beans.',
    examples: [
      { sentence: 'I drink a cup of black coffee every morning.', translation: 'Tôi uống một tách cà phê đen mỗi sáng.' },
      { sentence: 'Would you like some milk with your coffee?', translation: 'Bạn có muốn dùng thêm sữa với cà phê không?' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['beverage', 'morning'],
  },
  {
    id: 'vocab-hospital',
    targetText: 'Hospital',
    normalizedText: 'hospital',
    translation: 'Bệnh viện',
    phoneticUs: '/ˈhɑːspɪtl/',
    phoneticUk: '/ˈhɒspɪtl/',
    partOfSpeech: 'noun',
    cefrLevel: 'A1',
    category: 'Workplace',
    definitionEn: 'An institution providing medical treatment and nursing care for sick or injured people.',
    examples: [
      { sentence: 'She works as a dedicated nurse at the city hospital.', translation: 'Cô ấy làm y tá tận tâm tại bệnh viện thành phố.' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['health', 'medical'],
  },
  {
    id: 'vocab-family',
    targetText: 'Family',
    normalizedText: 'family',
    translation: 'Gia đình',
    phoneticUs: '/ˈfæməli/',
    phoneticUk: '/ˈfæməli/',
    partOfSpeech: 'noun',
    cefrLevel: 'A1',
    category: 'Daily Life',
    definitionEn: 'A group of one or more parents and their children living together as a unit.',
    examples: [
      { sentence: 'I love spending weekend evenings with my family.', translation: 'Tôi thích dành những buổi tối cuối tuần bên gia đình.' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['family', 'basics'],
  },

  // ==========================================================================
  // LEVEL A2: ELEMENTARY (SƠ CẤP)
  // ==========================================================================
  {
    id: 'vocab-travel',
    targetText: 'Travel',
    normalizedText: 'travel',
    translation: 'Đi du lịch / Di chuyển',
    phoneticUs: '/ˈtrævl/',
    phoneticUk: '/ˈtrævl/',
    partOfSpeech: 'verb',
    cefrLevel: 'A2',
    category: 'Travel & Leisure',
    definitionEn: 'To make a journey, typically of some length.',
    examples: [
      { sentence: 'They love to travel around Southeast Asia.', translation: 'Họ thích đi du lịch quanh khu vực Đông Nam Á.' },
      { sentence: 'I usually travel to work by bus.', translation: 'Tôi thường di chuyển đi làm bằng xe buýt.' },
    ],
    synonyms: ['journey', 'tour', 'visit'],
    imageUrl: 'https://images.unsplash.com/photo-1530521954074-e64f6810b32d?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['vacation', 'commute', 'journey'],
  },
  {
    id: 'vocab-planning',
    targetText: 'Planning',
    normalizedText: 'planning',
    translation: 'Lập kế hoạch',
    phoneticUs: '/ˈplænɪŋ/',
    phoneticUk: '/ˈplænɪŋ/',
    partOfSpeech: 'noun',
    cefrLevel: 'A2',
    category: 'Workplace',
    definitionEn: 'The process of making plans for something.',
    examples: [
      { sentence: 'Careful planning is essential for a successful trip.', translation: 'Lập kế hoạch cẩn thận là điều cốt yếu cho một chuyến đi thành công.' },
    ],
    synonyms: ['organizing', 'preparation'],
    source: 'curriculum',
    tags: ['work', 'project'],
  },
  {
    id: 'vocab-weather',
    targetText: 'Weather',
    normalizedText: 'weather',
    translation: 'Thời tiết',
    phoneticUs: '/ˈweðər/',
    phoneticUk: '/ˈweðə/',
    partOfSpeech: 'noun',
    cefrLevel: 'A2',
    category: 'Daily Life',
    definitionEn: 'The state of the atmosphere at a particular place and time.',
    examples: [
      { sentence: 'The weather is sunny and pleasant today.', translation: 'Thời tiết hôm nay nắng ráo và dễ chịu.' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=500&auto=format&fit=crop&q=80',
    source: 'curriculum',
    tags: ['nature', 'forecast'],
  },
  {
    id: 'vocab-schedule',
    targetText: 'Schedule',
    normalizedText: 'schedule',
    translation: 'Lịch trình / Thời khóa biểu',
    phoneticUs: '/ˈskedʒuːl/',
    phoneticUk: '/ˈʃedjuːl/',
    partOfSpeech: 'noun',
    cefrLevel: 'A2',
    category: 'Workplace',
    definitionEn: 'A plan for carrying out a process or procedure, giving lists of intended events and times.',
    examples: [
      { sentence: 'I have a very busy work schedule this week.', translation: 'Tuần này tôi có một lịch làm việc rất bận rộn.' },
    ],
    tags: ['toeic', 'work'],
  },

  // ==========================================================================
  // LEVEL B1: INTERMEDIATE (TRUNG CẤP)
  // ==========================================================================
  {
    id: 'vocab-collaborate',
    targetText: 'Collaborate',
    normalizedText: 'collaborate',
    translation: 'Cộng tác / Hợp tác',
    phoneticUs: '/kəˈlæbəreɪt/',
    phoneticUk: '/kəˈlæbəreɪt/',
    partOfSpeech: 'verb',
    cefrLevel: 'B1',
    category: 'Technology',
    definitionEn: 'To work jointly on an activity or project to produce something.',
    examples: [
      { sentence: 'Engineers collaborate across global teams to build innovative software.', translation: 'Các kỹ sư cộng tác qua các đội ngũ toàn cầu để xây dựng phần mềm đổi mới.' },
    ],
    synonyms: ['cooperate', 'partner', 'team up'],
    source: 'listening',
    tags: ['teamwork', 'tech', 'workplace'],
  },
  {
    id: 'vocab-ecosystem',
    targetText: 'Ecosystem',
    normalizedText: 'ecosystem',
    translation: 'Hệ sinh thái',
    phoneticUs: '/ˈiːkoʊsɪstəm/',
    phoneticUk: '/ˈiːkəʊsɪstəm/',
    partOfSpeech: 'noun',
    cefrLevel: 'B1',
    category: 'Environment',
    definitionEn: 'A biological community of interacting organisms and their physical environment.',
    examples: [
      { sentence: 'Reducing plastic waste is crucial to protect the coral reef ecosystem.', translation: 'Giảm rác thải nhựa là điều cốt yếu để bảo vệ hệ sinh thái rạn san hô.' },
    ],
    imageUrl: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=500&auto=format&fit=crop&q=80',
    source: 'listening',
    tags: ['marine', 'conservation', 'nature'],
  },
  {
    id: 'vocab-transform',
    targetText: 'Transform',
    normalizedText: 'transform',
    translation: 'Chuyển đổi / Biến đổi',
    phoneticUs: '/trænsˈfɔːrm/',
    phoneticUk: '/trænsˈfɔːm/',
    partOfSpeech: 'verb',
    cefrLevel: 'B1',
    category: 'Technology',
    definitionEn: 'To make a thorough or dramatic change in the form, appearance, or character of.',
    examples: [
      { sentence: 'Artificial intelligence is transforming traditional industries.', translation: 'Trí tuệ nhân tạo đang chuyển đổi các ngành công nghiệp truyền thống.' },
    ],
    synonyms: ['convert', 'revolutionize', 'alter'],
    source: 'listening',
    tags: ['ai', 'growth', 'change'],
  },
  {
    id: 'vocab-concussion',
    targetText: 'Concussion',
    normalizedText: 'concussion',
    translation: 'Chấn động não',
    phoneticUs: '/kənˈkʌʃ.ən/',
    phoneticUk: '/kənˈkʌʃ.ən/',
    partOfSpeech: 'noun',
    cefrLevel: 'B1',
    category: 'Health',
    definitionEn: 'Temporary unconsciousness or confusion caused by a blow to the head.',
    examples: [
      { sentence: 'The doctor confirmed he had a mild concussion.', translation: 'Bác sĩ xác nhận anh ấy bị chấn động não nhẹ.' },
    ],
    tags: ['medical', 'ted'],
  },
  {
    id: 'vocab-commencement',
    targetText: 'Commencement',
    normalizedText: 'commencement',
    translation: 'Lễ tốt nghiệp / Khởi đầu',
    phoneticUs: '/kəˈmens.mənt/',
    phoneticUk: '/kəˈmens.mənt/',
    partOfSpeech: 'noun',
    cefrLevel: 'B1',
    category: 'Education',
    definitionEn: 'A ceremony at which academic degrees or diplomas are conferred.',
    examples: [
      { sentence: 'Steve Jobs delivered a famous commencement speech at Stanford.', translation: 'Steve Jobs đã phát biểu một bài diễn thuyết tốt nghiệp nổi tiếng tại Stanford.' },
    ],
    tags: ['university', 'speech'],
  },

  // ==========================================================================
  // LEVEL B2: UPPER INTERMEDIATE (KHÁ GIỎI)
  // ==========================================================================
  {
    id: 'vocab-sustainable',
    targetText: 'Sustainable',
    normalizedText: 'sustainable',
    translation: 'Bền vững / Thân thiện môi trường',
    phoneticUs: '/səˈsteɪnəbl/',
    phoneticUk: '/səˈsteɪnəbl/',
    partOfSpeech: 'adjective',
    cefrLevel: 'B2',
    category: 'Environment',
    definitionEn: 'Able to be maintained at a certain rate or level without depleting natural resources.',
    examples: [
      { sentence: 'We must adopt sustainable energy solutions for our cities.', translation: 'Chúng ta phải áp dụng các giải pháp năng lượng bền vững cho các thành phố.' },
    ],
    synonyms: ['renewable', 'eco-friendly', 'viable'],
    source: 'dictionary',
    tags: ['green', 'energy', 'future'],
  },
  {
    id: 'vocab-articulate',
    targetText: 'Articulate',
    normalizedText: 'articulate',
    translation: 'Diễn đạt lưu loát / Rõ ràng',
    phoneticUs: '/ɑːrˈtɪkjuleɪt/',
    phoneticUk: '/ɑːˈtɪkjuleɪt/',
    partOfSpeech: 'verb',
    cefrLevel: 'B2',
    category: 'Education',
    definitionEn: 'Express an idea or feeling fluently and coherently.',
    examples: [
      { sentence: 'She was able to articulate her arguments with precision during the debate.', translation: 'Cô ấy có thể diễn đạt các lập luận của mình một cách chính xác trong cuộc tranh biện.' },
    ],
    synonyms: ['express', 'enunciate', 'communicate'],
    source: 'dictionary',
    tags: ['speaking', 'ielts', 'fluency'],
  },
  {
    id: 'vocab-perceive',
    targetText: 'Perceive',
    normalizedText: 'perceive',
    translation: 'Nhận thức / Cảm nhận',
    phoneticUs: '/pərˈsiːv/',
    phoneticUk: '/pəˈsiːv/',
    partOfSpeech: 'verb',
    cefrLevel: 'B2',
    category: 'Psychology',
    definitionEn: 'To interpret or look upon someone or something in a particular way.',
    examples: [
      { sentence: 'How we speak changes how our brains perceive the world.', translation: 'Cách chúng ta nói thay đổi cách bộ não nhận thức thế giới xung quanh.' },
    ],
    synonyms: ['discern', 'recognize', 'grasp'],
    tags: ['mind', 'ielts'],
  },
  {
    id: 'vocab-commitment',
    targetText: 'Commitment',
    normalizedText: 'commitment',
    translation: 'Sự cam kết / Tận tụy',
    phoneticUs: '/kəˈmɪt.mənt/',
    phoneticUk: '/kəˈmɪt.mənt/',
    partOfSpeech: 'noun',
    cefrLevel: 'B2',
    category: 'Workplace',
    definitionEn: 'The state or quality of being dedicated to a cause, activity, etc.',
    examples: [
      { sentence: 'Success requires dedication and strong long-term commitment.', translation: 'Thành công đòi hỏi sự cống hiến và cam kết lâu dài vững chắc.' },
    ],
    tags: ['toeic', 'work'],
  },

  // ==========================================================================
  // LEVEL C1: ADVANCED (CAO CẤP & IELTS 7.5+)
  // ==========================================================================
  {
    id: 'vocab-ubiquitous',
    targetText: 'Ubiquitous',
    normalizedText: 'ubiquitous',
    translation: 'Phổ biến khắp nơi / Nhan nhản',
    phoneticUs: '/juːˈbɪk.wə.t̬əs/',
    phoneticUk: '/juːˈbɪk.wɪ.təs/',
    partOfSpeech: 'adjective',
    cefrLevel: 'C1',
    category: 'Technology',
    definitionEn: 'Present, appearing, or found everywhere.',
    examples: [
      { sentence: 'Smartphones have become ubiquitous in modern society.', translation: 'Điện thoại thông minh đã trở nên phổ biến khắp mọi nơi trong xã hội hiện đại.' },
    ],
    synonyms: ['omnipresent', 'pervasive', 'universal'],
    tags: ['ielts', 'advanced', 'academic'],
  },
  {
    id: 'vocab-resilience',
    targetText: 'Resilience',
    normalizedText: 'resilience',
    translation: 'Khả năng phục hồi / Sự kiên cường',
    phoneticUs: '/rɪˈzɪl.jəns/',
    phoneticUk: '/rɪˈzɪl.jəns/',
    partOfSpeech: 'noun',
    cefrLevel: 'C1',
    category: 'Psychology',
    definitionEn: 'The capacity to recover quickly from difficulties; toughness.',
    examples: [
      { sentence: 'Emotional resilience helps entrepreneurs overcome severe setbacks.', translation: 'Sự kiên cường về mặt cảm xúc giúp các nhà khởi nghiệp vượt qua những trở ngại nghiêm trọng.' },
    ],
    synonyms: ['endurance', 'adaptability', 'fortitude'],
    tags: ['ielts', 'mindset'],
  },
  {
    id: 'vocab-disseminate',
    targetText: 'Disseminate',
    normalizedText: 'disseminate',
    translation: 'Phổ biến / Truyền bá rộng rãi',
    phoneticUs: '/dɪˈsem.ə.neɪt/',
    phoneticUk: '/dɪˈsem.ɪ.neɪt/',
    partOfSpeech: 'verb',
    cefrLevel: 'C1',
    category: 'Education',
    definitionEn: 'To spread or disperse (something, especially information) widely.',
    examples: [
      { sentence: 'Universities aim to disseminate knowledge to society.', translation: 'Các trường đại học hướng tới việc phổ biến kiến thức cho xã hội.' },
    ],
    tags: ['academic', 'ielts'],
  },
];
