import { SpeakingPrompt } from '@linguaflow/domain';

export const MASTER_SPEAKING_PROMPTS: SpeakingPrompt[] = [
  // 1. PRONUNCIATION
  {
    id: 'sp-pron-01',
    title: 'Minimal Pair: Ship vs Sheep (/ɪ/ vs /iː/)',
    description: 'Luyện tập phân biệt nguyên âm ngắn /ɪ/ và nguyên âm dài /iː/.',
    mode: 'pronunciation',
    difficulty: 'beginner',
    topic: 'Phonetics',
    targetWords: ['ship', 'sheep', 'fit', 'feet'],
    targetPhrases: ['The sheep is on the ship.'],
    sampleAnswer: 'The sheep is on the ship.',
    durationSeconds: 15,
    minWords: 3,
    maxWords: 15,
    cefr: 'A1',
    tags: ['pronunciation', 'minimal-pairs', 'vowels'],
  },
  {
    id: 'sp-pron-02',
    title: 'Consonant Cluster: /θ/ vs /s/ (Think vs Sink)',
    description: 'Luyện tập phát âm âm thổi lưỡi /θ/ không bị nhầm lẫn sang /s/.',
    mode: 'pronunciation',
    difficulty: 'elementary',
    topic: 'Phonetics',
    targetWords: ['think', 'sink', 'thought', 'sought'],
    targetPhrases: ['I think the ship will sink.'],
    sampleAnswer: 'I think the ship will sink.',
    durationSeconds: 15,
    minWords: 3,
    maxWords: 15,
    cefr: 'A2',
    tags: ['pronunciation', 'consonants', 'th-sound'],
  },

  // 2. REPETITION
  {
    id: 'sp-rep-01',
    title: 'Daily Greeting and Introduction (A1)',
    description: 'Lặp lại câu chào hỏi và giới thiệu bản thân chuẩn ngữ điệu.',
    mode: 'repetition',
    difficulty: 'beginner',
    topic: 'Daily Life',
    targetWords: ['engineer', 'pleasure', 'meeting'],
    targetPhrases: ['Nice to meet you', 'software engineer'],
    sampleAnswer: "Hello, my name is Alex and I am a software engineer.",
    durationSeconds: 20,
    minWords: 5,
    maxWords: 20,
    cefr: 'A1',
    tags: ['repetition', 'greetings', 'a1'],
  },
  {
    id: 'sp-rep-02',
    title: 'Giving Clear Directions in the City (B1)',
    description: 'Lặp lại câu chỉ đường mạch lạc với các liên từ chỉ hướng.',
    mode: 'repetition',
    difficulty: 'intermediate',
    topic: 'Travel',
    targetWords: ['intersection', 'straight', 'opposite'],
    targetPhrases: ['turn left at the intersection', 'walk straight ahead'],
    sampleAnswer: "Go straight ahead for two blocks, then turn left at the intersection opposite the museum.",
    durationSeconds: 25,
    minWords: 8,
    maxWords: 25,
    cefr: 'B1',
    tags: ['repetition', 'directions', 'b1'],
  },

  // 3. SHADOWING
  {
    id: 'sp-shad-01',
    title: 'Morning Routine & Healthy Habits (A2)',
    description: 'Nói đuổi đồng thời theo nhịp điệu của người bản xứ về thói quen buổi sáng.',
    mode: 'shadowing',
    difficulty: 'elementary',
    topic: 'Daily Life',
    targetWords: ['routine', 'stretching', 'refreshing'],
    targetPhrases: ['start my day', 'cup of warm water'],
    sampleAnswer: "Every morning, I wake up early, do some stretching, and drink a cup of warm water to start my day.",
    durationSeconds: 30,
    minWords: 10,
    maxWords: 35,
    cefr: 'A2',
    tags: ['shadowing', 'routine', 'a2'],
  },
  {
    id: 'sp-shad-02',
    title: 'Workplace Collaboration & Agile Standup (B2)',
    description: 'Luyện tập ngữ điệu chuyên nghiệp trong buổi họp báo cáo tiến độ công việc.',
    mode: 'shadowing',
    difficulty: 'upper-intermediate',
    topic: 'Workplace',
    targetWords: ['collaboration', 'milestone', 'prioritize'],
    targetPhrases: ['completed the user interface', 'focus on testing'],
    sampleAnswer: "Yesterday, our team completed the user interface milestone, and today we will prioritize performance testing.",
    durationSeconds: 40,
    minWords: 15,
    maxWords: 45,
    cefr: 'B2',
    tags: ['shadowing', 'workplace', 'b2'],
  },

  // 4. GUIDED SPEAKING
  {
    id: 'sp-gui-01',
    title: 'Introducing Your Hometown and Culture (A2)',
    description: 'Trả lời lần lượt 4 câu hỏi định hướng để tạo thành bài nói hoàn chỉnh.',
    mode: 'guided',
    difficulty: 'elementary',
    topic: 'Culture & Places',
    targetWords: ['famous', 'traditional', 'atmosphere', 'hospitable'],
    targetPhrases: ['located in', 'well-known for', 'friendly people'],
    sampleAnswer: "I was born in a coastal city. It is well-known for delicious seafood and hospitable residents.",
    durationSeconds: 60,
    minWords: 20,
    maxWords: 80,
    cefr: 'A2',
    tags: ['guided', 'hometown', 'a2'],
    steps: [
      'Where is your hometown located?',
      'What is the weather like throughout the year?',
      'What are the most famous dishes or tourist spots?',
      'Why do you enjoy living or visiting there?',
    ],
  },
  {
    id: 'sp-gui-02',
    title: 'Discussing Career Aspirations and Goals (B2)',
    description: 'Trình bày định hướng phát triển nghề nghiệp theo cấu trúc logic.',
    mode: 'guided',
    difficulty: 'upper-intermediate',
    topic: 'Career',
    targetWords: ['aspiration', 'expertise', 'leadership', 'initiative'],
    targetPhrases: ['in the next five years', 'broaden my horizon'],
    sampleAnswer: "In the next five years, I aspire to enhance my technical expertise and take on leadership initiatives.",
    durationSeconds: 90,
    minWords: 35,
    maxWords: 120,
    cefr: 'B2',
    tags: ['guided', 'career', 'b2'],
    steps: [
      'What is your current field of study or work?',
      'What specific skills are you actively improving?',
      'What key milestone do you want to achieve in the next 3 to 5 years?',
      'How will you overcome potential industry challenges?',
    ],
  },

  // 5. PICTURE SPEAKING
  {
    id: 'sp-pic-01',
    title: 'Describe a Bustling Modern Cafe Scene',
    description: 'Mô tả chi tiết các hoạt động, con người và không gian trong quán cà phê.',
    mode: 'picture',
    difficulty: 'intermediate',
    topic: 'Daily Life',
    targetWords: ['bustling', 'barista', 'laptop', 'cozy'],
    targetPhrases: ['in the foreground', 'in the background', 'enjoying a cup of coffee'],
    sampleAnswer: "In the picture, I see a bustling cafe where customers are working on laptops while the barista prepares drinks.",
    durationSeconds: 60,
    minWords: 25,
    maxWords: 100,
    cefr: 'B1',
    tags: ['picture', 'cafe', 'description'],
    imagePrompt: 'A warm cozy cafe with wooden tables, people typing on laptops, and a barista crafting latte art.',
  },
  {
    id: 'sp-pic-02',
    title: 'Describe an International Airport Terminal',
    description: 'Mô tả khung cảnh hành khách check-in và di chuyển tại sân bay quốc tế.',
    mode: 'picture',
    difficulty: 'intermediate',
    topic: 'Travel',
    targetWords: ['terminal', 'passengers', 'departure', 'luggage'],
    targetPhrases: ['checking their boarding passes', 'heading toward the gate'],
    sampleAnswer: "The image depicts a spacious airport terminal with passengers carrying luggage towards the departure gates.",
    durationSeconds: 60,
    minWords: 25,
    maxWords: 100,
    cefr: 'B1',
    tags: ['picture', 'airport', 'travel'],
    imagePrompt: 'Modern international airport departure hall with large glass windows and travelers rolling suitcases.',
  },

  // 6. SITUATION SPEAKING
  {
    id: 'sp-sit-01',
    title: 'Hotel Check-in and Requesting a Quiet Room',
    description: 'Nhập vai khách hàng làm thủ tục nhận phòng tại khách sạn quốc tế.',
    mode: 'situation',
    difficulty: 'intermediate',
    topic: 'Travel',
    targetWords: ['reservation', 'confirmation', 'quiet', 'amenities'],
    targetPhrases: ['I have a reservation under the name of', 'would it be possible to'],
    sampleAnswer: "Good afternoon, I have a reservation under the name of John Smith. Could I please have a quiet room on a high floor?",
    durationSeconds: 60,
    minWords: 20,
    maxWords: 80,
    cefr: 'B1',
    tags: ['situation', 'hotel', 'roleplay'],
    scenario: 'You arrive at a 4-star hotel in London after a long flight. Confirm your booking and politely ask for a non-smoking, quiet room.',
  },
  {
    id: 'sp-sit-02',
    title: 'Job Interview: Handling a Team Conflict Question',
    description: 'Trả lời câu hỏi phỏng vấn về cách xử lý bất đồng quan điểm trong nhóm làm việc.',
    mode: 'situation',
    difficulty: 'advanced',
    topic: 'Workplace',
    targetWords: ['perspective', 'constructive', 'compromise', 'resolution'],
    targetPhrases: ['open communication', 'reach a mutual agreement'],
    sampleAnswer: "When facing a disagreement, I prioritize active listening to understand their perspective, followed by open discussion to reach a constructive compromise.",
    durationSeconds: 90,
    minWords: 35,
    maxWords: 130,
    cefr: 'C1',
    tags: ['situation', 'interview', 'c1'],
    scenario: 'The interviewer asks: "Tell me about a time you disagreed with a colleague on a project and how you resolved it."',
  },

  // 7. FREE SPEAKING
  {
    id: 'sp-free-01',
    title: 'Impact of Artificial Intelligence on Future Education',
    description: 'Trình bày quan điểm cá nhân về cách AI thay đổi phương pháp học tập và giảng dạy.',
    mode: 'free-speaking',
    difficulty: 'upper-intermediate',
    topic: 'Technology',
    targetWords: ['personalized', 'automation', 'critical thinking', 'accessible'],
    targetPhrases: ['in my opinion', 'on the one hand', 'furthermore'],
    sampleAnswer: "In my opinion, artificial intelligence makes learning highly personalized and accessible, though human mentorship remains indispensable.",
    durationSeconds: 90,
    minWords: 35,
    maxWords: 150,
    cefr: 'B2',
    tags: ['free-speaking', 'technology', 'ai'],
  },
  {
    id: 'sp-free-02',
    title: 'Sustainable Living and Environmental Protection',
    description: 'Thảo luận về các hành động thiết thực mà mỗi cá nhân có thể làm để bảo vệ môi trường.',
    mode: 'free-speaking',
    difficulty: 'advanced',
    topic: 'Environment',
    targetWords: ['sustainability', 'carbon footprint', 'biodegradable', 'conservation'],
    targetPhrases: ['take responsibility', 'shift towards renewable energy'],
    sampleAnswer: "To protect our planet, adopting sustainable habits such as reducing single-use plastics and minimizing our carbon footprint is crucial.",
    durationSeconds: 120,
    minWords: 40,
    maxWords: 180,
    cefr: 'C1',
    tags: ['free-speaking', 'environment', 'c1'],
  },
];
