import {
  SocialProfile,
  LearningActivity,
  StudyNote,
  StudyGroup,
  Achievement,
} from '@linguaflow/domain';

export const SAMPLE_PROFILES: SocialProfile[] = [
  {
    userId: 'demo-user-id-001',
    username: 'minhtran',
    displayName: 'Minh Trần (Bạn)',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    bio: 'Đang chinh phục IELTS 7.5 & TOEIC 900+ cùng LinguaFlow 🚀',
    targetLanguage: 'English',
    level: 'B2',
    totalXP: 1450,
    currentStreak: 5,
    totalLearningDays: 24,
    vocabularyLearned: 380,
    listeningSessions: 18,
    writingSubmissions: 9,
    readingCompleted: 12,
    examsCompleted: 4,
    privacy: {
      profileVisibility: 'public',
      activityVisibility: 'public',
      allowFriendRequests: true,
      allowGroupInvites: true,
      showOnLeaderboard: true,
      showAchievements: true,
    },
    createdAt: '2026-01-15T08:00:00.000Z',
  },
  {
    userId: 'user-alice-002',
    username: 'alicenguyen',
    displayName: 'Alice Nguyễn',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    bio: 'IELTS Tutor & Chuyên viên ngôn ngữ học. Chia sẻ kinh nghiệm luyện viết mỗi ngày.',
    targetLanguage: 'English',
    level: 'C1',
    totalXP: 3200,
    currentStreak: 19,
    totalLearningDays: 62,
    vocabularyLearned: 850,
    listeningSessions: 42,
    writingSubmissions: 35,
    readingCompleted: 40,
    examsCompleted: 12,
    privacy: {
      profileVisibility: 'public',
      activityVisibility: 'public',
      allowFriendRequests: true,
      allowGroupInvites: true,
      showOnLeaderboard: true,
      showAchievements: true,
    },
    createdAt: '2026-01-01T08:00:00.000Z',
  },
  {
    userId: 'user-kenji-003',
    username: 'kenjisato',
    displayName: 'Kenji Sato',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    bio: 'JLPT N2 & English Enthusiast. Let us study together!',
    targetLanguage: 'Japanese',
    level: 'B1',
    totalXP: 2100,
    currentStreak: 12,
    totalLearningDays: 45,
    vocabularyLearned: 520,
    listeningSessions: 30,
    writingSubmissions: 14,
    readingCompleted: 22,
    examsCompleted: 8,
    privacy: {
      profileVisibility: 'public',
      activityVisibility: 'public',
      allowFriendRequests: true,
      allowGroupInvites: true,
      showOnLeaderboard: true,
      showAchievements: true,
    },
    createdAt: '2026-02-01T08:00:00.000Z',
  },
  {
    userId: 'user-linhdan-004',
    username: 'linhdan',
    displayName: 'Linh Đan',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=200&auto=format&fit=crop&q=80',
    bio: 'Học sinh chuyên Anh. Mục tiêu VSTEP C1 trước tháng 12.',
    targetLanguage: 'English',
    level: 'B2',
    totalXP: 1850,
    currentStreak: 8,
    totalLearningDays: 31,
    vocabularyLearned: 440,
    listeningSessions: 22,
    writingSubmissions: 18,
    readingCompleted: 19,
    examsCompleted: 6,
    privacy: {
      profileVisibility: 'public',
      activityVisibility: 'public',
      allowFriendRequests: true,
      allowGroupInvites: true,
      showOnLeaderboard: true,
      showAchievements: true,
    },
    createdAt: '2026-02-10T08:00:00.000Z',
  },
];

export const SAMPLE_ACTIVITIES: LearningActivity[] = [
  {
    id: 'act-001',
    userId: 'user-alice-002',
    userName: 'Alice Nguyễn',
    userAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    type: 'exam_completed',
    title: 'TOEIC Official Format Mock Test 01 (990/990)',
    description: 'Đạt điểm tuyệt đối 990/990 với độ chính xác 100%!',
    visibility: 'public',
    timestamp: new Date(Date.now() - 3600 * 1000 * 2).toISOString(),
  },
  {
    id: 'act-002',
    userId: 'demo-user-id-001',
    userName: 'Minh Trần (Bạn)',
    userAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    type: 'reading_completed',
    title: 'The Ecology of Urban Pollinators (IELTS Academic)',
    description: 'Đọc hiểu 285 WPM, trả lời đúng 100% câu hỏi.',
    visibility: 'public',
    timestamp: new Date(Date.now() - 3600 * 1000 * 5).toISOString(),
  },
  {
    id: 'act-003',
    userId: 'user-kenji-003',
    userName: 'Kenji Sato',
    userAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
    type: 'streak_milestone',
    title: 'Đạt chuỗi học tập 12 ngày liên tiếp! 🔥',
    visibility: 'public',
    timestamp: new Date(Date.now() - 3600 * 1000 * 12).toISOString(),
  },
];

export const SAMPLE_STUDY_NOTES: StudyNote[] = [
  {
    id: 'note-001',
    userId: 'user-alice-002',
    authorName: 'Alice Nguyễn',
    authorAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&auto=format&fit=crop&q=80',
    title: 'Cách dùng In / On / At trong mốc thời gian không bao giờ nhầm',
    content: `1. IN: Dùng cho khoảng thời gian lớn (Năm, Tháng, Mùa, Thế kỷ)\n- In 2026, in December, in summer, in the 21st century.\n\n2. ON: Dùng cho ngày cụ thể và thứ trong tuần\n- On Monday, on my birthday, on Christmas Day, on July 14th.\n\n3. AT: Dùng cho thời điểm chính xác và các dịp lễ chung\n- At 3:00 PM, at noon, at midnight, at weekend, at Christmas.`,
    tags: ['grammar', 'prepositions', 'ielts', 'toeic'],
    visibility: 'public',
    reactionCount: 14,
    reactions: { helpful: 8, inspiring: 4, useful: 2 },
    commentCount: 3,
    createdAt: '2026-02-12T10:00:00.000Z',
    updatedAt: '2026-02-12T10:00:00.000Z',
  },
  {
    id: 'note-002',
    userId: 'demo-user-id-001',
    authorName: 'Minh Trần',
    authorAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
    title: 'Top 5 Collocations điểm cao cho bài thi Writing Task 2',
    content: `1. Pose a severe threat to (Gây mối đe dọa nghiêm trọng tới)\n2. Mitigate the adverse effects of (Giảm thiểu tác động tiêu cực của)\n3. Foster sustainable economic development (Thúc đẩy phát triển kinh tế bền vững)\n4. Bridge the socioeconomic gap (Thu hẹp khoảng cách kinh tế - xã hội)\n5. Allocate financial resources into (Phân bổ nguồn lực tài chính vào)`,
    tags: ['writing', 'collocations', 'c1-vocab'],
    visibility: 'public',
    reactionCount: 9,
    reactions: { helpful: 6, inspiring: 2, useful: 1 },
    commentCount: 2,
    createdAt: '2026-02-13T14:00:00.000Z',
    updatedAt: '2026-02-13T14:00:00.000Z',
  },
];

export const SAMPLE_STUDY_GROUPS: StudyGroup[] = [
  {
    id: 'group-toeic-900',
    name: 'Chiến Binh TOEIC 900+ ETS',
    description: 'Cùng giải đề thi thử TOEIC mỗi ngày, chữa lỗi sai Part 5 & 7 và nâng cao phản xạ nghe Part 1-4.',
    topic: 'TOEIC Prep',
    level: 'B2',
    ownerId: 'user-alice-002',
    memberCount: 4,
    maxMembers: 50,
    visibility: 'public',
    totalGroupXP: 5800,
    coverImage: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-01-20T08:00:00.000Z',
  },
  {
    id: 'group-ielts-75',
    name: 'IELTS Academic Writing & Reading Master',
    description: 'Thảo luận dàn ý Task 2, phân tích từ vựng Band 8+ và luyện đọc các bài báo học thuật quốc tế.',
    topic: 'IELTS Academic',
    level: 'C1',
    ownerId: 'demo-user-id-001',
    memberCount: 3,
    maxMembers: 30,
    visibility: 'public',
    totalGroupXP: 4200,
    coverImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=500&auto=format&fit=crop&q=80',
    createdAt: '2026-02-01T08:00:00.000Z',
  },
];

export const SAMPLE_ACHIEVEMENTS: (Achievement & { currentProgress?: number; isUnlocked?: boolean })[] = [
  {
    id: 'ach-1',
    code: 'FIRST_NOTE',
    title: 'Người Chia Sẻ Tri Thức',
    description: 'Tạo và chia sẻ ghi chú học tập đầu tiên cho cộng đồng.',
    icon: 'BookOpen',
    category: 'study',
    xpReward: 25,
    maxProgress: 1,
    currentProgress: 1,
    isUnlocked: true,
  },
  {
    id: 'ach-2',
    code: 'STUDY_BUDDY',
    title: 'Bạn Cùng Tiến',
    description: 'Kết bạn với 3 bạn học trên LinguaFlow.',
    icon: 'UserPlus',
    category: 'social',
    xpReward: 30,
    maxProgress: 3,
    currentProgress: 2,
    isUnlocked: false,
  },
  {
    id: 'ach-3',
    code: 'GROUP_LEADER',
    title: 'Thủ Lĩnh Biệt Đội',
    description: 'Gia nhập hoặc thành lập nhóm học tập.',
    icon: 'Shield',
    category: 'social',
    xpReward: 40,
    maxProgress: 1,
    currentProgress: 1,
    isUnlocked: true,
  },
  {
    id: 'ach-4',
    code: 'HELPFUL_AUTHOR',
    title: 'Cây Bút Vàng',
    description: 'Nhận được 10 lượt tương tác hữu ích trên các bài viết.',
    icon: 'Sparkles',
    category: 'study',
    xpReward: 50,
    maxProgress: 10,
    currentProgress: 8,
    isUnlocked: false,
  },
  {
    id: 'ach-5',
    code: 'STREAK_WARRIOR',
    title: 'Ngọn Lửa Bền Bỉ',
    description: 'Duy trì chuỗi học tập 7 ngày liên tục.',
    icon: 'Flame',
    category: 'streak',
    xpReward: 50,
    maxProgress: 7,
    currentProgress: 5,
    isUnlocked: false,
  },
];
